### PR TITLE
SAC agent working on Pendulum-v0

### PR DESCRIPTION
**Pull request by janislavjankov**
A lot of todo items:
- adjust the alpha parameter according to the target entropy
- pytorch support
- support container action spaces
- save/restore of the agent
- summaries

### CODE REVIEW

**Comment by michaelschaarschmidt** [comment]
Thanks so much for the PR!

Seems there is a small merge conflict in the agent:

```
<<<<<<< master
        #self._q_vars_splitter = ContainerSplitter(*q_names, scope="q_vars_splitter")
=======
        self._q_vars_splitter = ContainerSplitter(*q_names, scope="q_vars_splitter")
>>>>>>> sac_development
```

**Comment by sven1977** [comment]
Hi Janislav, thanks so much for the PR. We'll take care of it most likely this weekend.

**Comment by janislavjankov** [comment]
Fixed the conflicts

**Comment by sven1977** [comment]
I will merge this in the SAC branch now and then make sure it goes into master asap.
Thanks again!

**Comment by janislavjankov** [comment]
Yeah there is some clean up to follow - update to master, go over all of the todos I introduced, etc. This is more of a preview. Thanks for the support!

**Pull request merged**
